#devil emoji in python
import turtle as t
t.speed(50)
t.begin_fill()
t.fillcolor('#8F0A7A')
t.circle(100)
t.end_fill()
t.penup()
t.left(90)
t.forward(100)
t.left(90)
t.forward(23)
t.pendown()
t.pencolor('black')
t.begin_fill()
t.fillcolor('black')
t.circle(10)
t.end_fill()
t.right(-160)
def eybrow():
    t.begin_fill()
    t.fillcolor('black')
    for i in range(8):
        t.forward(-5)
        t.left(1)

    t.left(170)
    for i in range(20):
        t.forward(1)
        t.right(5)
    t.right(90)
    for i in range(5):
        t.forward(6)
        t.left(-1)
    t.left(10)
    for i in range(10):
        t.forward(4)
        t.left(1)
    t.right(180)
    for i in range(3):
        t.forward(1)
        t.right(-1)
    t.forward(9)
    t.end_fill()

eybrow()
t.left(90)
t.penup()
t.forward(10)
t.left(90)
t.forward(40)
t.pendown()
t.begin_fill()
t.fillcolor('black')
t.circle(10)
t.end_fill()
t.left(90)
t.forward(20)
t.left(120)
t.begin_fill()
t.fillcolor('black')
for i in range(8):
    t.forward(-5)
    t.left(1)

t.left(170)
for i in range(20):
    t.forward(1)
    t.left(5)
t.left(96)
for i in range(5):
    t.forward(6)
    t.left(-1)
t.left(10)
for i in range(10):
    t.forward(4)
    t.right(1)
t.right(180)
for i in range(3):
    t.forward(1)
    t.left(-1)
t.forward(9)
t.end_fill()

t.right(90)
t.penup()
t.forward(50)
t.right(90)
t.pendown()
t.begin_fill()
t.fillcolor('black')
t.left(10)
for i in range(18):
    t.forward(5)
    t.right(4)
t.end_fill()
t.right(25)
t.penup()
t.forward(100)
t.left(20)
t.pendown()
t.begin_fill()
t.fillcolor('#840A8B')
for i in range(20):
    t.forward(3)
    t.right(3)
t.right(160)
for i in range(52):
    t.forward(1)
    t.left(2)
t.end_fill()
t.right(20)
t.penup()
t.forward(132)
t.pendown()
t.begin_fill()
t.fillcolor('#840A8B')
t.left(20)
for i in range(52):
    t.forward(1)
    t.left(2)
t.left(180)
for i in range(22):
    t.forward(3)
    t.right(3)
t.end_fill()
t.done()
