#flag of Thailand
import turtle

screen = turtle.Screen()
screen.setup(width = 1.0, height = 1.0)

def draw():
    turtle.penup()
    turtle.goto(-500, 200)
    turtle.color("black")
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("RED")
    turtle.left(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(90)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(300, 200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("WHITE")
    turtle.left(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-500, -40)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("BLUE")
    turtle.left(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.forward(800)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(300, -40)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("WHITE")
    turtle.left(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-500, -220)
    turtle.pendown()
    turtle.begin_fill()
    turtle.fillcolor("RED")
    turtle.left(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.right(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(800)
    turtle.end_fill()
    turtle.done()
draw()
    
    
    
    
