#google assistant logo in Python

import turtle as t
t.hideturtle()
t.begin_fill()
t.fillcolor("blue")
t.circle(80)
t.end_fill()
t.penup()
t.goto(150,0)
t.pendown()
t.begin_fill()
t.fillcolor("red")
t.circle(40)
t.end_fill()
t.penup()
t.goto(150,-120)
t.pendown()
t.begin_fill()
t.fillcolor("yellow")
t.circle(50)
t.end_fill()
t.penup()
t.goto(205,95)
t.pendown()
t.begin_fill()
t.fillcolor("green")
t.circle(20)
t.end_fill()
t.penup()
t.goto(-100,-200)
t.pendown()
FONTSIZE = 25
FONT = ('Arial', FONTSIZE, 'normal')
t.write('Google Assistant logo by Pooja Patel', font=FONT)
t.done()
