
Learn.python
49 minutes ago
import turtle
turtle.Turtle()
turtle.penup()
turtle.goto(-40,30)
turtle.pendown()
turtle.begin_fill()
turtle.color("black","yellow")
turtle.forward(55)
turtle.left(120)
turtle.forward(14)
turtle.left(60)
turtle.forward(50)
for i in range(18):
    turtle.forward(1)
    turtle.right(5)
turtle.forward(40)
turtle.left(60)
turtle.forward(14)
turtle.left(120)
turtle.forward(58)
for i in range(18):
    turtle.forward(1)
    turtle.left(5)

turtle.forward(20)
turtle.end_fill()
turtle.begin_fill()
turtle.color("black","red")
turtle.forward(110)
for i in range(18):
    turtle.forward(1)
    turtle.left(5)
turtle.forward(50)
turtle.left(60)
turtle.forward(14)
turtle.left(120)
turtle.forward(44)
for i in range(18):
    turtle.forward(1)
    turtle.right(5)
turtle.forward(56)
turtle.left(120)
turtle.forward(14)
turtle.end_fill()
turtle.penup()
turtle.back(14)
turtle.left(150)
turtle.forward(20)
turtle.right(90)
turtle.pendown()
turtle.penup()
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(79)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.color("black","blue")
turtle.forward(60)
for i in range(18):
    turtle.forward(1)
    turtle.left(5)
turtle.forward(40)
turtle.right(60)
turtle.forward(20)
turtle.left(60)
turtle.forward(30)
turtle.left(60)
turtle.forward(20)
turtle.right(60)
turtle.forward(40)
for i in range(18):
    turtle.forward(1)
    turtle.left(5)
turtle.forward(43)
turtle.left(60)
turtle.forward(14)
turtle.left(120)
turtle.forward(35)
for i in range(18):
    turtle.forward(1)
    turtle.right(5)
turtle.forward(106)
for i in range(18):
    turtle.forward(1)
    turtle.right(5)
turtle.forward(40)
turtle.end_fill()
turtle.begin_fill()
turtle.color("black","green")
turtle.left(60)
turtle.forward(14)
turtle.left(120)
turtle.forward(60)
for i in range(18):
    turtle.forward(1)
    turtle.left(5)
turtle.forward(40)
turtle.left(120)
turtle.forward(16)
turtle.left(60)
turtle.forward(19)
for i in range(18):
    turtle.forward(1)
    turtle.right(5)
turtle.forward(40)
turtle.left(60)
turtle.forward(14)
turtle.end_fill()
turtle.penup()
turtle.back(14)
turtle.left(30)
turtle.back(65)
turtle.right(90)
turtle.forward(20)
turtle.left(90)
turtle.pendown()
turtle.begin_fill()
turtle.color("black",'blue')


for i in range(100):
    turtle.forward(2)
    turtle.left(5)
turtle.end_fill()
turtle.done()
