#olymptrade logo in Python
import turtle as t
t.hideturtle()
t.bgcolor("black")
t.penup()
t.goto(-10,-20)
t.pendown()
t.pensize(35)
t.pencolor("white")
t.circle(120)
t.pensize(0)
t.penup()
t.goto(-105,-50)
t.pendown()
t.begin_fill()
t.fillcolor("green")
t.forward(200)
t.left(120)
t.forward(200)
t.left(120)
t.forward(200)
t.end_fill()
t.done()
